server:
  port: 8080

spring:
    thymeleaf:
        cache: false    #thymeleaf模板缓存，生产环境下建议设置为true
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/ptqx4
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
          initial-size: 5   #初始化连接数
          min-idle: 5       #最小连接数
          max-active: 10    #最大连接数
          max-wait: 60000   #最大等待时间
          time-between-eviction-runs-millis: 60000   #多长时间检查连接是否空闲
          min-evictable-idle-time-millis: 60000
          test-while-idle: true    #是否在程序空闲时进行连接检查，默认true
          test-on-borrow: false    #程序在向连接池拿连接时，是否进行连接检查，默认false，影响性能
          test-on-return: false    #程序在向连接池还连接时，是否进行连接检查，默认false，影响性能
          pool-prepared-statements: true    #打开PSCache
          max-pool-prepared-statement-per-connection-size: 20    #指定每个连接上PSCache的大小
          filters: stat,wall,log4j
          connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          use-global-data-source-stat: true
#    redis:
#      host: 192.168.42.129
#      port: 16379
#      database: 0
#    session:
#      store-type: none
#    cache:
#      type: redis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: net.htjs.pt4.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql