server:
  port: 9002
spring:
  application:
    name: provider
eureka:
  instance:
    ip-address: 192.168.30.32
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
